### PR TITLE
Add instructions how to enable WiFi on the Odin board

### PR DESCRIPTION
**Pull request by bulislaw**
CC: @c1728p9

### CODE REVIEW

**Comment by c1728p9** [comment]
Looks good to me

**Comment by bulislaw** [comment]
@0xc0170 could you merge this, we don't seem to have access rights.

**Comment by 0xc0170** [comment]
LGTM but we should use different repo during OOB ? LEt me know, I'll merge this as soon as possible if needed.

**Comment by bulislaw** [comment]
I guess we don't need it, we should backport change from the oob example.

**Pull request closed without merging**
