### PR TITLE
Return error for platforms without D0/D1 pins defined

### PR DESCRIPTION
**Pull request by bulislaw**
@adbridge @bridadan

### CODE REVIEW

**Comment by 0xc0170** [comment]
@sg- any comments for this patch?

**Comment by bulislaw** [comment]
I think the ultimate fix would be to have, another, higher level pin names layer defined (the LED1, BTN1, SPI1_MOSI, I2C1_SDA and so on) that together with claimed capabilities would make us more platform independent.

**Comment by 0xc0170** [comment]
> I think the ultimate fix would be to have, another, higher level pin names layer defined (the LED1, BTN1, SPI1_MOSI, I2C1_SDA and so on) that together with claimed capabilities would make us more platform independent.

We had in mbed-os defined TEST_ pins, for i2c (``YOTTA_CFG_HARDWARE_TEST_PINS_I2C_SDA`` example), spi etc. Each platform would provide those, and we would use it for testing and examples. We might want to do the same?

**Comment by bulislaw** [comment]
Wouldn't it be nice to have short usable name that we can expose to users as well? I know that portability between platforms is not that simple, but that would be a step in good direction, making things more consistent and hopefully easier to use for ppl.

**Comment by 0xc0170** [comment]
> Wouldn't it be nice to have short usable name that we can expose to users as well

would , but LED_x or I2C_SDA, are already taken by targets, we got also for buttons

For instance from STM32 nucloe F429:

```
    // Generic signals namings
    LED1        = PG_13, // Corresponds to LD3 on MB1075B
    LED2        = PG_14, // Corresponds to LD4 on MB1075B
    LED3        = PG_13,
    LED4        = PG_14,
    LED_RED     = LED2,
    USER_BUTTON = PA_0,
    SERIAL_TX   = PA_9,
    SERIAL_RX   = PA_10,
    USBTX       = PA_9,
    USBRX       = PA_10,
    SPI_MOSI    = PA_7,
    SPI_MISO    = PA_6,
    SPI_SCK     = PA_5,
    SPI_CS      = PB_6,
```

This is not though a rule, so ot all targets have SPI_ pins for instance. Might be worth to push for these pins and we use them in tests/examples.

**Comment by adbridge** [comment]
I'd be happy to see this fix go in as an initial solution so we can get all the examples green again. Then look at more generic solutions later ?

**Comment by bulislaw** [comment]
Ah yes of course, we should get that in if everyone is happy with it.

**Comment by sg-** [comment]
Seems reasonable. Would also just suggest we look at that field in targets.json and make sure the boards actually use it. I don't recall this being widely used.

**Comment by bulislaw** [comment]
On hold due to #3152

**Pull request merged**
