### PR TITLE
Update to latest esp8266-driver

### PR DESCRIPTION
**Pull request by sarahmarshy**
Updated the lib reference to the latest esp8266 driver. 

@geky and @adbridge, could you review this?

### CODE REVIEW

**Comment by geky** [comment]
Looks good to me, did you run the example locally for sanity?

**Comment by sarahmarshy** [comment]
@brandonboesch is going to run it. We are a little short on ESP8266s right now.

**Comment by adbridge** [comment]
LGTM can you post test results here once done please ?

**Comment by brandonboesch** [comment]
I ran this example with the latest driver and was able to connect and send http request successfully.

**Comment by sarahmarshy** [comment]
Bump

**Comment by deepikabhavnani** [comment]
@bulislaw @geky - Please merge this PR

**Comment by geky** [comment]
Can do

**Comment by geky** [comment]
I don't have access to this repo, it's up to @bulislaw

**Comment by bulislaw** [comment]
It doesn't work with the 'official firmware', using ESP with some random firmware i got and error I need to use one from here: https://developer.mbed.org/teams/ESP8266/wiki/Firmware-Update
Now I'm getting:
```
WiFi example

Scan:
0 networks available.

Connecting...

Connection error
```

Debug:
```
WiFi example

Scan:
0 networks available.

Connecting...

Connection error
WiFi example

SWiFi example

Scan:
AT> AT+CWLAP
AT> AT+CWLAP
0 networks available.

Connecting...
AT> AT+RST
AT> AT+RST

Connection error
```
Weirdly we don't seem to get anything back I think Sam had the same issues very recently. I've tried to connect to the ESP over serial and manually check AT but the board seems dead. @sarahmarshy @geky can you test the firmware following the instructions above using another board.

**Comment by deepikabhavnani** [comment]
@bulislaw - I have verified example after firmware update with below versions. Also @geky fixed the release tag yesterday (v1.3) after verifying tests of esp8266 driver. 
mbed os 5.5
esp8266 - tag v1.3 /  cac4d0d8f97745fe9a613b705b406646aeacc3e2

**Comment by bulislaw** [comment]
Did you flash the ESP using this guide? https://developer.mbed.org/teams/ESP8266/wiki/Firmware-Update ?

**Comment by deepikabhavnani** [comment]
Yes

**Comment by deepikabhavnani** [comment]
FYI: After firmware update i get below versions for my device:
```
AT< AT+GMR
AT< AT version:1.3.0.0(Jul 14 2016 18:54:01)
AT= SDK version:2
AT< .0.0(656edbf)
AT< compile time:Jul 19 2016 18:44:44
```
Also, We need to reset the device after flash update else scan and connect will fail in example (I kind of missed it once)

SerialPassthrough program was not working for K66F when used directly from online compiler, but offline project with latest mbed-os works.

**Comment by bulislaw** [comment]
Flashing from windows works fine and subsequent flashes from esptool work as well. Merging.

**Pull request merged**
